### ISSUE TITLE
Can you create a licence for FormatWith

### ISSUE THREAD

**Issue by michelleskothe** [crozone/FormatWith#1]
Hi, In order to include your library in our project we need it to have a licence. Can you create one? MIT would be preferable.

thanks

Michelle

**Comment by crozone** [comment]
Will get on this right away, MIT license looks good.

**Comment by crozone** [comment]
Done, MIT license added.

**Comment by michelleskothe** [comment]
Hi Ryan,

Many thanks.

Ciao,

Michelle


[Intelledox Pty Ltd]<http://www.intelledox.com/>

Michelle Kothe |  Software Developer
[http://www.intelledox.com/wp-content/uploads/2014/05/phoneIcon.png] +61 (02) 6280 6244  |  [http://www.intelledox.com/wp-content/uploads/2014/05/mobileIcon.png]  +61 (0)422 513 001
[http://www.intelledox.com/wp-content/uploads/2014/05/eMailIcon.png] michelle.kothe@intelledox.com  |  [http://www.intelledox.com/wp-content/uploads/2014/05/skypeIcon.png]  intelledox_michellek
[http://www.intelledox.com/wp-content/uploads/2014/05/homeIcon.png] intelledox.com<http://www.intelledox.com/>

Please notify us if you have received this in error. Information transmitted is expressly for the use of the intended recipient only. Any review, re-transmission, printing, storage, disclosure, dissemination, taking of any action in reliance upon, or other use of this information by persons or entities other than the intended recipient is prohibited and may be punishable by law. If you have received this email and any attachments in error, please notify the sender immediately.

P We believe in reducing the cost and impact of paper waste. Let us show you how.<http://www.intelledox.com/ix-connect/paperless-organization-just-green-dream/>
