### ISSUE TITLE
Just a thank you.

### ISSUE THREAD

**Issue by AmbroiseCouissin** [crozone/FormatWith#11]
Hi @crozone,

I just wanted to thank you for the library. Very nicely done!

Here are a few suggestions just in case you have some time to waste :)
- Supporting arrays. I used my own handler for that.
- Supporting other template languages like shopify's liquid (https://help.shopify.com/themes/liquid/basics) or mustache (https://github.com/janl/mustache.js/)

**Comment by crozone** [comment]
@AmbroiseCouissin Thanks for the kind words! Apologies it has taken so long to address your suggestions.

* I'm beginning work on adding arrays, except I will be trying to add support for indexers in general, such that other types like `Dictionary<T,U>` will work too. Added as issue https://github.com/crozone/FormatWith/issues/26.

* Other templating languages are probably a little too outside the scope of this library and would likely be best served by dedicated formatting libraries for those specific templating languages. However, Mustache could theoretically be implemented relatively easily by using a different tokenizer. I might do a mockup and see how it works.

Cheers!
