### ISSUE TITLE
Assembly signing / strong naming

### ISSUE THREAD

**Issue by JeremySkinner** [crozone/FormatWith#18]
Hi Ryan,

It would be good if the assembly could be signed. 

Although strong naming is a PITA, Microsoft's recommendation for OSS projects it that [OSS libraries should be signed](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming#create-strong-named-net-libraries), so that they can be used by both projects which are strong named, and those the aren't (if the assembly isn't strong-named, then it won't be able to be loaded by end-user projects which are strong named, especially in net4x which has strict assembly loading). 

FluentValidation is strong named because of this, so FormatWith would need to be as well if we decide to take a dependency on it in the end.

**Comment by JeremySkinner** [comment]
(I'd be happy to submit a PR for this)

**Comment by crozone** [comment]
I've whipped up a PR, does this look about right?

https://github.com/crozone/FormatWith/pull/19

If so I'll merge and bump the version and redeploy as 3.0.1.

**Comment by JeremySkinner** [comment]
Looks good to me!

**Comment by crozone** [comment]
I have released v3.0.1, let me know if that co-operates with other strong signed projects.
