### ISSUE TITLE
Suggest using IReadOnlyDictionary<> instead of IDictionary<>

### ISSUE THREAD

**Issue by guillep2k** [crozone/FormatWith#22]
Hi, if possible, I'd suggest supporting `IReadOnlyDictionary<>`, rather than `IDictionary<>` (probably both?), as sometimes the object is.... read-only.

**Comment by crozone** [comment]
Makes perfect sense. I'll roll this into the 4.0 milestone.

**Comment by crozone** [comment]
Completed as of commit 6e600371875af9644b28f63745d2d85a12b32af4, will be included in 4.0 release.

**Comment by crozone** [comment]
Closing this since it's implemented on 4.0 and I want the little milestone graph to go up.
